#!/bin/sh
# This script syncs any changes from the real /boot on the SD card to the virtual /boot on the USB media.
#
# Part of pitools - https://github.com/zipplet/pitools
# Copyright (c) Michael Nixon 2016.

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
CYAN='\033[1;36m'
NC='\033[0m'

PROGNAME="rpi-usbroot"
FAKEBOOT="/boot"
REALBOOT="/bootsd"
INSTALLMARKDIR="/pitools"
INSTALLMARK="sd_to_usb_boot"
INSTALLMARKFILE="${INSTALLMARKDIR}/${INSTALLMARK}"

# We must run as root
if [ "$(id -u)" != "0" ]; then
   echo "${RED}Please run ${PROGNAME} as root${NC}" 1>&2
   exit 1
fi

if [ ! -f "$INSTALLMARKFILE" ]; then
  echo "${RED}${INSTALLMARK} is not installed, bailing!.${NC}"
  exit 1
fi

echo "${CYAN}${PROGNAME}: Version 0.2 (20161014)"
echo "${CYAN}${PROGNAME}: Copyright (c) Michael Nixon 2016"

if [ ! -d "$REALBOOT" ]; then
  echo "${CYAN}${PROGNAME}${NC}: ${RED}CRITICAL${NC}: ${CYAN}${REALBOOT}${NC} does not exist."
  echo "${CYAN}${PROGNAME}${NC}: ${RED}CRITICAL${NC}: Giving up - something is badly wrong."
  exit 1
fi

if ! grep -qs "$REALBOOT" /proc/mounts; then
  echo "${CYAN}${PROGNAME}${NC}: ${RED}CRITICAL${NC}: ${CYAN}${REALBOOT}${NC} not mounted."
  echo "${CYAN}${PROGNAME}${NC}: ${YELLOW}Are you trying to run this after boot?${NC}"
  echo "${CYAN}${PROGNAME}${NC}: Perhaps you intended to run ${YELLOW}rpi-usbbootsync${NC} instead?"
  echo "${CYAN}${PROGNAME}${NC}: Please see the documentation for more information."
  echo "${CYAN}${PROGNAME}${NC}: ${RED}CRITICAL${NC}: Giving up - something is badly wrong."
  exit 1
fi


if [ ! -d "$FAKEBOOT" ]; then
  echo "${CYAN}${PROGNAME}${NC}: ${YELLOW}WARNING${NC}: ${CYAN}${FAKEBOOT}${NC} not found on the USB media"
  mkdir /boot
  echo "${CYAN}${PROGNAME}${NC}: ${YELLOW}WARNING${NC}: Created ${CYAN}${FAKEBOOT}${NC} on the USB media"
  echo "${CYAN}${PROGNAME}${NC}: ${YELLOW}WARNING${NC}: Initial sync may take longer than usual."
fi

echo "${CYAN}${PROGNAME}${NC}: ${GREEN}Syncing any boot partition changes${NC}"
if ! rsync -ax /bootsd/ /boot; then
  echo "${CYAN}${PROGNAME}${NC}: ${RED}CRITICAL${NC}: Sync failed"
  exit 1
fi
if ! umount /bootsd; then
  echo "${CYAN}${PROGNAME}${NC}: ${RED}CRITICAL${NC}: Unmount failed"
  exit 1
else
  echo "${CYAN}${PROGNAME}${NC}: ${GREEN}Success, unmounted the SD card${NC}"
fi

exit 0
