#!/bin/sh
# This script syncs changes on demand from the virtual /boot on the USB media to the real boot on the SD card.

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
CYAN='\033[1;36m'
NC='\033[0m'

PROGNAME="rpi-usbbootsync"
FAKEBOOT="/boot"
REALBOOT="/bootsd"

echo "${PROGNAME}: Version 0.1 (20161010)"
echo "${PROGNAME}: Copyright (c) Michael Nixon 2016"

if [ ! -d "$REALBOOT" ]; then
  echo "${PROGNAME}: ${RED}CRITICAL${NC}: ${CYAN}${REALBOOT}${NC} does not exist."
  echo "${PROGNAME}: ${RED}CRITICAL${NC}: Giving up - something is badly wrong."
  exit 1
fi

if [ ! -d "$FAKEBOOT" ]; then
  echo "${PROGNAME}: ${RED}CRITICAL${NC}: ${CYAN}${FAKEBOOT}${NC} does not exist."
  echo "${PROGNAME}: ${RED}CRITICAL${NC}: Giving up - something is badly wrong."
  exit 1
fi

if ! grep -qs "$REALBOOT" /proc/mounts; then
  echo "${PROGNAME}: Mounting the boot partition from the SD card..."
  if ! mount /bootsd; then
    echo "${PROGNAME}: ${RED}CRITICAL${NC}: Failed to mount ${CYAN}${REALBOOT}${NC}"
    exit 1
  fi
else
  echo "${PROGNAME}: ${YELLOW}WARNING${NC}: ${CYAN}${REALBOOT}${NC} was already mounted."
fi

# Double check we did actually mount it
if ! grep -qs "$REALBOOT" /proc/mounts; then
  echo "${PROGNAME}: ${RED}CRITICAL${NC}: Mount succeeded, but cannot see it"
  exit 1
fi

echo "${PROGNAME}: ${GREEN}Syncing any boot partition changes${NC}"
if ! rsync -ax /boot/ /bootsd; then
  echo "${PROGNAME}: ${RED}CRITICAL${NC}: Sync failed"
  exit 1
fi
if ! umount /bootsd; then
  echo "${PROGNAME}: ${RED}CRITICAL${NC}: Unmount failed"
  exit 1
else
  echo "${PROGNAME}: ${GREEN}Success, unmounted the SD card${NC}"
fi

exit 0
