#!/bin/sh
# Configure the hardware clock after the first reboot
#
# Part of pitools - https://github.com/zipplet/pitools
# Copyright (c) Michael Nixon 2016.

# Colours
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
CYAN='\033[1;36m'

# Reset to black
NC='\033[0m'

# Location we place our install mark files in
INSTALLMARKDIR="/pitools"
INSTALLMARK="ds3231_setup"
INSTALLMARKFILE="${INSTALLMARKDIR}/${INSTALLMARK}"

# We must run as root
if [ "$(id -u)" != "0" ]; then
   echo "${RED}Please run this program as root (or use sudo)${NC}" 1>&2
   exit 1
fi

if [ ! -f "$INSTALLMARKFILE" ]; then
  echo "${RED}${INSTALLMARK} is not installed.${NC}"
  exit 1
fi

date
echo
read -p "Is the date and time displayed above correct? (y/n) :" -r ANSWER
echo
if [ ! "$ANSWER" = "y" ]; then
  echo "Aborting. Set the clock first or wait for ntpd to do it!"
  exit 1
fi

echo "${GREEN}Reconfiguring ntp...${NC}"
systemctl stop ntp
rm /var/lib/ntp/ntp.drift
timedatectl set-ntp 1

echo "${GREEN}Removing any old adjtime file...${NC}"
rm /etc/adjtime

echo "${GREEN}Setting the hardware clock...${NC}"
hwclock -w

echo "${GREEN}All done. A reboot is required as soon as possible.${NC}"

echo "${GREEN}"
read -p "Would you like to reboot the Raspberry Pi now? (y/n) :" -r ANSWER
echo "${NC}"
if [ ! "$ANSWER" = "y" ]; then
  exit 1
fi

reboot
exit 0
